### ISSUE TITLE
CoD BSP Decompiler error

### ISSUE THREAD

**Issue by EugenyP** [wfowler1/bsp-decompiler#1]
Opening file D:\Games\Call of Duty\Main\maps\credits.bsp
BSP v59 (Call of Duty)
Internal version number: 1347633796 (TYPE_COD)
Planes lump: 7880288 bytes, 492518 items
Texture lump: 272 bytes, 3 items
WARNING: Funny lump size in Texture
Models lump: 9894572 bytes, 206136 items
WARNING: Funny lump size in Models
Brushes lump: 8564544 bytes, 2141136 items
Brush sides lump: 8267376 bytes, 1033422 items
Decompiling...

Exception caught in job 1: System.NullReferenceException: Object reference not set to an instance of the object.
   в BSP46Decompiler.decompile() в d:\A_CODE\bsp-decompiler-master\Decompiler\BSP46Decompiler.cs:line 51
   в DecompilerThread.Run() в d:\A_CODE\bsp-decompiler-master\Decompiler\DecompilerThread.cs:line 131

**Comment by wfowler1** [comment]
Just an update on this issue: Don't worry, I haven't ignored you! I've rewritten essentially the entire program based on the LibBSP library, with a focus on keeping the code clean. This issue won't be an issue anymore once it's completed.

**Comment by EugenyP** [comment]
Any progress?

**Comment by wfowler1** [comment]
Oh, yes... Sorry, it's been a long time with lots of Life Stuff getting in the way, but... I committed the rewrite on Jan 31 of 2016, and I've fixed a few bugs since then. I don't have my CoD install right now so I can't test it against that specific BSP, but I've tested it against a couple of other BSPs I got off the internet and currently it seems to work. Can you try it out against credits.bsp and report results here? Thanks.

Make sure when you do a pull you also pull submodules.

**Comment by EugenyP** [comment]
Yes, it's working.

Is it possible to convert the terrain?

**Comment by wfowler1** [comment]
I would absolutely love to add support for the terrain as well, but I can't find any documentation of the format of the data structures anywhere. The closest thing I could find was this: http://wiki.modsrepository.com/index.php?title=Call_of_Duty_1:_d3dbsp

Reverse engineering of the format is difficult. I have the same problem with MoHAA maps as well. But I've reinstalled the game from Steam so I have maps I can look at. I just don't know what I'm looking at.

**Comment by wfowler1** [comment]
Closing this issue since it's solved. For the terrain problem see #3
